const USERNAME_OR_PASSWORD_IS_REQUIRED = 'USERNAME_OR_PASSWORD_IS_REQUIRED'
const USER_IS_ALREADY_EXIST = 'USER_IS_ALREADY_EXIST'

module.exports = {
  USERNAME_OR_PASSWORD_IS_REQUIRED,
  USER_IS_ALREADY_EXIST
}